import Head from 'next/head';
import Greating from '@/component/greating';
import Aboutme from '@/component/aboutme';
// import { Projects } from '@/component/projects';
// import Contact from '@/component/contact';
// import Footer from '@/component/footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Roganda's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Greating />
        <Aboutme />
        {/* <Projects />
        <Contact />
        <Footer /> */}
      </main>
    </>
  )
}
